### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by novio8** [wcdnail/TwoTreesSapphirePro#1]
Hi, 
is there an English version ?
thanx
Anzo

**Comment by wcdnail** [comment]
Hi. Yes.
Change #define LCD_LANGUAGE ru to en
Configuration.h, line 1648

**Comment by novio8** [comment]
OK, thank you.
Do you experience any problems with your Sapphire Pro, usin your version ?

**Comment by wcdnail** [comment]
No, but now I not so often use my printer
