### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by novio8** [wcdnail/TwoTreesSapphirePro#2]
I downloaded your files and I get the following Error.
I use Visual Studio Code  and Platformio

*** [.pio/build/mks_robin_nano/src/src/HAL/HAL_STM32F1/dogm/u8g_com_stm32duino_fsmc.cpp.o] Error 1

thanx

**Comment by wcdnail** [comment]
Probably U8glib error. You need another version of it.

**Comment by wcdnail** [comment]
Try this out, eng version 
[Robin_nano.zip](https://github.com/wcdnail/TwoTreesSapphirePro/files/4148262/Robin_nano.zip)

**Comment by wcdnail** [comment]
I use U8glib-HAL 0.4.1

**Comment by novio8** [comment]
I don't have TMC driver for Z and E, I have stock configuration.
I downloaded your package of Marlin and I'm getting the following error
*** [.pio/build/mks_robin_nano/src/src/HAL/HAL_STM32F1/dogm/u8g_com_stm32duino_fsmc.cpp.o] Error 1

**Comment by wcdnail** [comment]
Too short error description. Do you try install U8glib-HAL 0.4.1?

**Comment by wcdnail** [comment]
[U8glib-HAL_ID1932.zip](https://github.com/wcdnail/TwoTreesSapphirePro/files/4151674/U8glib-HAL_ID1932.zip)
Unpack it to %USERPROFILE%\.platformio\lib
Delete all other versions of U8glib (SapphirePro\Marlin2\.pio\libdeps\mks_robin_nano\...)

**Comment by wcdnail** [comment]
![image](https://user-images.githubusercontent.com/1853016/73718937-f0aa9400-472e-11ea-832d-96c29c8e96aa.png)

**Comment by novio8** [comment]
I followed your instructions and Compile finished without an Error
I will flash Sapphire later Today and let you know how it went
thanx

**Comment by novio8** [comment]
I'v run a test print and it seems Sapphire runs as expected

**Comment by wcdnail** [comment]
Glad to hear that. Welcome
